version: '3'

services:
  http-static:
    image: daiapache2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-static.rule=PathPrefix(`/`)"
      - "traefik.http.services.web-static.loadbalancer.sticky.cookie.name=sticky_session_static_web"
    scale: 3

  http-dyn:
    image: daiexpress
    command: node .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-dyn.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.http-dyn-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.http-dyn.middlewares=http-dyn-stripprefix"
    scale: 2

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock